name: Build App

on:
  push:
    branches:
      - develop
  pull_request:
    branches: [develop]

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Show git-hosted machine information
        run: uname -a
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: Checkout repo from develop branch
        uses: actions/checkout@v4
        with:
          ref: develop
      - name: Install npm dependency
        run: npm install
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: |
          cd android
          ./gradlew bundleRelease
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.4
          release_name: Release v1.0.4
          draft: false
          prerelease: false
      - name: Upload APK to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: android/app/build/outputs/bundle/release/app-release.aab
          asset_name: app-release.aab
          asset_content_type: application/vnd.android.package-archive
  ios-build:
    name: iOS Build-
    runs-on: macos-latest
    steps:
      - name: Checkout repo from develop branch
        uses: actions/checkout@v4
        with:
          ref: develop
      - name: Install dependencies
        run: |
          brew install cocoapods
          npm install
          cd ios
          pod install
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'
      - name: Build iOS app
        run: |
          xcodebuild -workspace ecoChargerLocatorApp.xcworkspace -scheme ecoChargerLocatorApp -configuration Release -sdk iphoneos build archive -archivePath $PWD/build/ecoChargerLocatorApp.xcarchive
          xcodebuild -exportArchive -archivePath $PWD/build/ecoChargerLocatorApp.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.4
          release_name: Release v1.0.4
          draft: false
          prerelease: false
      - name: Upload IPA to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/ecoChargerLocatorApp/ecoChargerLocatorApp.ipa
          asset_name: ecoChargerLocatorApp.ipa
          asset_content_type: application/octet-stream